### ISSUE TITLE
Table components should extend HtmlComponent, if suitable

### ISSUE THREAD

**Issue by brunovianarezende** [stefanuebe/html-table#5]
It seems to me the TableBody component should extend the com.vaadin.flow.component.HtmlContainer class, since it contains other components. Or, at least the com.vaadin.flow.component.HtmlComponent class. This would allow one to do things like add css classes to them.

**Comment by stefanuebe** [comment]
I think extending HtmlComponent might make sense here as it is already for other parts the case. HtmlContainer is not possible as it would allow "injecting" non conform elements into the table body (which only may contain table rows by spec).

I also extend this issue to check other part, if they also should / could extend HtmlComponent.

**Comment by brunovianarezende** [comment]
In vaadin 24 all components inherit from HasStyles (https://github.com/vaadin/flow/pull/15742), so it is one reason less to change TBody and other components.

**Comment by stefanuebe** [comment]
Yep. Due to this I would for now close this issue as I do not really see reason to extend HTMLComponent. The only things it also adds are the title attribute and the HasSize interface, from which the tbody element only supports the height setting (widths, min-/max-height are not).

If there are other reasons, that I am not aware of to still extend this class, please reopen and give some feedback.
